In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

url = "https://menzil.mr/"  

response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

prices = []
divs1 = soup.find_all('div', class_='bottom-text-block')
for div in divs1:
    price = div.find('span', class_='price').text.strip()
    price = re.sub(r'[^\d]', '', price)  # Remove non-digit characters
    prices.append(price)

data1 = {'Price (MRO)': prices}
df = pd.DataFrame(data1)

data2 = {'Area (m²)': [], 'Location': []}
divs2 = soup.find_all('div', class_='container-card')
for div in divs2:
    area = div.find('div', class_='prop-area').text.strip()
    area = re.findall(r'\d+', area)[0]  # Extract the first number in the string
    location = div.find('div', class_='marker-text location').text.strip()
    data2['Area (m²)'].append(area)
    data2['Location'].append(location)

df2 = pd.DataFrame(data2)

df_combined = pd.concat([df, df2], axis=1)
df_combined.head(20)

# Save the dataframe as a CSV file
df_combined.to_csv('data.csv', index=False)

   Price (MRO) Area (m²)                      Location
0     53000000       190         لاس بالماس, تفرغ زينة
1     65000000       300           القطاع 5, تفرغ زينة
2    350000000       600        سيتَه اصمار, تفرغ زينة
3     38500000       165         سيته ابلاج, تفرغ زينة
4      7500000       180    المطار القديم,  دار النعيم
5     35000000       360  سمعة ولد اخطيره,  دار النعيم
6      3700000       800           الصحراوي, تفرغ زينة
7     16000000       400    المطار القديم,  دار النعيم
8     42000000       600           القطاع 5, تفرغ زينة
9     16000000       345            كابيتال, تفرغ زينة
10    27000000       600           القطاع 5, تفرغ زينة
11   550000000      1000            كابيتال, تفرغ زينة
12    21000000       216                المشروع, تيارت
13    12000000       180                 كارفور, عرفات
14    53000000       190         لاس بالماس, تفرغ زينة
15    30000000       430       ولد الشيباني, تفرغ زينة
16    85000000       500           الصحراوي, تفرغ زينة
17    35000000       900           القطاع 5, تفرغ زينة
18     3000000       150                الفلوجة, عرفات
19    35000000       600           القطاع 5, تفرغ زينة

In [7]:
import pandas as pd


# Create a dictionary to store the mapping of locations to zone numbers
zone_dict = {}

# Assign a unique zone number to each different location
zone_counter = 1
for location in df_combined['Location'].unique():
    zone_dict[location] = zone_counter
    zone_counter += 1

# Create a new column 'Zone Number' in the dataframe and assign the zone numbers
df_combined['Zone Number'] = df_combined['Location'].map(zone_dict)

print(df_combined.head(10))

# Print the zone dictionary
print(zone_dict)

  Price (MRO) Area (m²)                      Location  Zone Number
0    53000000       190         لاس بالماس, تفرغ زينة            1
1    65000000       300           القطاع 5, تفرغ زينة            2
2   350000000       600        سيتَه اصمار, تفرغ زينة            3
3    38500000       165         سيته ابلاج, تفرغ زينة            4
4     7500000       180    المطار القديم,  دار النعيم            5
5    35000000       360  سمعة ولد اخطيره,  دار النعيم            6
6     3700000       800           الصحراوي, تفرغ زينة            7
7    16000000       400    المطار القديم,  دار النعيم            5
8    42000000       600           القطاع 5, تفرغ زينة            2
9    16000000       345            كابيتال, تفرغ زينة            8
{'لاس بالماس, تفرغ زينة': 1, 'القطاع 5, تفرغ زينة': 2, 'سيتَه اصمار, تفرغ زينة': 3, 'سيته ابلاج, تفرغ زينة': 4, 'المطار القديم,  دار النعيم': 5, 'سمعة ولد اخطيره,  دار النعيم': 6, 'الصحراوي, تفرغ زينة': 7, 'كابيتال, تفرغ زينة': 8, 'المشروع, تيارت': 9, 'كارفور, عرفات': 10, 'ولد الشيباني, تفرغ زينة': 11, 'الفلوجة, عرفات': 12, 'الدَّاية 6, عرفات': 13, 'بوحديدة, توجونين': 14, 'الزعتر,  دار النعيم': 15, 'إيلو سي, لكصر': 16, 'فيراج ولد ابادو,  دار النعيم': 17, 'كارفور المقاومة,  دار النعيم': 18, 'عين الطلح, تيارت': 19, 'دار السلام, تيارت': 20, 'الدَّاية الرابعة, عرفات': 21, 'ملّح, توجونين': 22, 'أه نور, تفرغ زينة': 23, 'اف نور, تفرغ زينة': 24, 'بيكة 9, الرياض': 25, 'الدَّاية 15, عرفات': 26, 'الدَّايات الثلاثة, عرفات': 27}

In [8]:
import pandas as pd

# Create a dictionary to store the mapping of locations to zone numbers
zone_dict = {}

# Assign a unique zone number to each different location
zone_counter = 1
for location in df_combined['Location'].unique():
    zone_dict[location] = zone_counter
    zone_counter += 1

df_without_location = df_combined.drop('Location', axis=1)

df_without_location['Zone Number'] = df_combined['Location'].map(zone_dict)

print(df_without_location.head(10))

# Print the zone dictionary
print(zone_dict)

  Price (MRO) Area (m²)  Zone Number
0    53000000       190            1
1    65000000       300            2
2   350000000       600            3
3    38500000       165            4
4     7500000       180            5
5    35000000       360            6
6     3700000       800            7
7    16000000       400            5
8    42000000       600            2
9    16000000       345            8
{'لاس بالماس, تفرغ زينة': 1, 'القطاع 5, تفرغ زينة': 2, 'سيتَه اصمار, تفرغ زينة': 3, 'سيته ابلاج, تفرغ زينة': 4, 'المطار القديم,  دار النعيم': 5, 'سمعة ولد اخطيره,  دار النعيم': 6, 'الصحراوي, تفرغ زينة': 7, 'كابيتال, تفرغ زينة': 8, 'المشروع, تيارت': 9, 'كارفور, عرفات': 10, 'ولد الشيباني, تفرغ زينة': 11, 'الفلوجة, عرفات': 12, 'الدَّاية 6, عرفات': 13, 'بوحديدة, توجونين': 14, 'الزعتر,  دار النعيم': 15, 'إيلو سي, لكصر': 16, 'فيراج ولد ابادو,  دار النعيم': 17, 'كارفور المقاومة,  دار النعيم': 18, 'عين الطلح, تيارت': 19, 'دار السلام, تيارت': 20, 'الدَّاية الرابعة, عرفات': 21, 'ملّح, توجونين': 22, 'أه نور, تفرغ زينة': 23, 'اف نور, تفرغ زينة': 24, 'بيكة 9, الرياض': 25, 'الدَّاية 15, عرفات': 26, 'الدَّايات الثلاثة, عرفات': 27}